DROP TABLE IF EXISTS auth_sessions CASCADE;
DROP TABLE IF EXISTS schema_migrations CASCADE;
DROP TABLE IF EXISTS drill_results CASCADE;
DROP TABLE IF EXISTS session_drills CASCADE;
DROP TABLE IF EXISTS workout_sessions CASCADE;
DROP TABLE IF EXISTS workout_drills CASCADE;
DROP TABLE IF EXISTS drills CASCADE;
DROP TABLE IF EXISTS workouts CASCADE;
DROP TABLE IF EXISTS users CASCADE;

